# Generated by Django 4.0.3 on 2022-04-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='datacleaner/files', verbose_name='CSV XLS XLSX')),
                ('clean_null', models.BooleanField()),
                ('fill_null', models.BooleanField()),
                ('clean_duplicate', models.BooleanField()),
            ],
        ),
    ]
