# Generated by Django 4.0.3 on 2022-04-21 20:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacleaner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datainput',
            name='fill',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='datainput',
            name='upload',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'xls', 'xlsx'])]),
        ),
    ]
