# Generated by Django 4.0.3 on 2022-04-22 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacleaner', '0003_rename_fill_datainput_filling_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datainput',
            name='clean_duplicate',
        ),
        migrations.RemoveField(
            model_name='datainput',
            name='clean_null',
        ),
    ]
